import Header from "@/components/Header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "kideHJOfbns4URNInTmtAcLxH-1ouvbOkGe-jj60l0o",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          background: "#fbfaf0",
          color: "#000",
          margin: 0
        }}
      >

        <Header />

        <main style={{ maxWidth: "1100px", margin: "0 auto", padding: "20px" }}>
          <div style={{ paddingTop: "100px" }}>
            {children}
          </div>
        </main>
        <Script
          id="plerdy-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
    var _protocol="https:"==document.location.protocol?"https://":"http://";
    _site_hash_code="6f42d72ba604695b0ef24b8224408e79",_suid=73375,plerdyScript=document.createElement("script");
    plerdyScript.setAttribute("defer",""),plerdyScript.dataset.plerdymainscript="plerdymainscript",
    plerdyScript.src="https://a.plerdy.com/public/js/click/main.js?v="+Math.random();
    var plerdymainscript=document.querySelector("[data-plerdymainscript='plerdymainscript']");
    plerdymainscript&&plerdymainscript.parentNode.removeChild(plerdymainscript);
    try{document.head.appendChild(plerdyScript)}catch(t){console.log(t,"unable add script tag")}
    `,
          }}
        />
      </body>
    </html>
  );
}

