import Header from "@/components/Header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "kideHJOfbns4URNInTmtAcLxH-1ouvbOkGe-jj60l0o",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          background: "#fbfaf0",
          color: "#000",
          margin: 0
        }}
      >

        <Header />

        <main style={{ maxWidth: "1100px", margin: "0 auto", padding: "20px" }}>
          <div style={{ paddingTop: "100px" }}>
            {children}
          </div>
        </main>

      </body>
    </html>
  );
}

